//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekRequestMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    [System.SerializableAttribute()]
    public partial class SendRdwKeuringsverzoekRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Voertuig VoertuigField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Garage GarageField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Keuringsverzoek KeuringsverzoekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Voertuig Voertuig {
            get {
                return this.VoertuigField;
            }
            set {
                if ((object.ReferenceEquals(this.VoertuigField, value) != true)) {
                    this.VoertuigField = value;
                    this.RaisePropertyChanged("Voertuig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Garage Garage {
            get {
                return this.GarageField;
            }
            set {
                if ((object.ReferenceEquals(this.GarageField, value) != true)) {
                    this.GarageField = value;
                    this.RaisePropertyChanged("Garage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Keuringsverzoek Keuringsverzoek {
            get {
                return this.KeuringsverzoekField;
            }
            set {
                if ((object.ReferenceEquals(this.KeuringsverzoekField, value) != true)) {
                    this.KeuringsverzoekField = value;
                    this.RaisePropertyChanged("Keuringsverzoek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voertuig", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.SerializableAttribute()]
    public partial class Voertuig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private string kentekenField;
        
        private string merkField;
        
        private string typeField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Klant eigenaarField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Persoon bestuurderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string kenteken {
            get {
                return this.kentekenField;
            }
            set {
                if ((object.ReferenceEquals(this.kentekenField, value) != true)) {
                    this.kentekenField = value;
                    this.RaisePropertyChanged("kenteken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string merk {
            get {
                return this.merkField;
            }
            set {
                if ((object.ReferenceEquals(this.merkField, value) != true)) {
                    this.merkField = value;
                    this.RaisePropertyChanged("merk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Klant eigenaar {
            get {
                return this.eigenaarField;
            }
            set {
                if ((object.ReferenceEquals(this.eigenaarField, value) != true)) {
                    this.eigenaarField = value;
                    this.RaisePropertyChanged("eigenaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Persoon bestuurder {
            get {
                return this.bestuurderField;
            }
            set {
                if ((object.ReferenceEquals(this.bestuurderField, value) != true)) {
                    this.bestuurderField = value;
                    this.RaisePropertyChanged("bestuurder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Garage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    [System.SerializableAttribute()]
    public partial class Garage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NaamField;
        
        private string PlaatsField;
        
        private string KvkField;
        
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Plaats {
            get {
                return this.PlaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaatsField, value) != true)) {
                    this.PlaatsField = value;
                    this.RaisePropertyChanged("Plaats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Kvk {
            get {
                return this.KvkField;
            }
            set {
                if ((object.ReferenceEquals(this.KvkField, value) != true)) {
                    this.KvkField = value;
                    this.RaisePropertyChanged("Kvk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keuringsverzoek", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    [System.SerializableAttribute()]
    public partial class Keuringsverzoek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string CorrolatieIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CorrolatieId {
            get {
                return this.CorrolatieIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrolatieIdField, value) != true)) {
                    this.CorrolatieIdField = value;
                    this.RaisePropertyChanged("CorrolatieId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klant", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Persoon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Leasemaatschappij))]
    public partial class Klant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private long klantnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long klantnummer {
            get {
                return this.klantnummerField;
            }
            set {
                if ((this.klantnummerField.Equals(value) != true)) {
                    this.klantnummerField = value;
                    this.RaisePropertyChanged("klantnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoon", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.SerializableAttribute()]
    public partial class Persoon : Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Klant {
        
        private string voornaamField;
        
        private string tussenvoegselField;
        
        private string achternaamField;
        
        private string adresField;
        
        private string postcodeField;
        
        private string woonplaatsField;
        
        private string telefoonnummerField;
        
        private string emailadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string voornaam {
            get {
                return this.voornaamField;
            }
            set {
                if ((object.ReferenceEquals(this.voornaamField, value) != true)) {
                    this.voornaamField = value;
                    this.RaisePropertyChanged("voornaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string tussenvoegsel {
            get {
                return this.tussenvoegselField;
            }
            set {
                if ((object.ReferenceEquals(this.tussenvoegselField, value) != true)) {
                    this.tussenvoegselField = value;
                    this.RaisePropertyChanged("tussenvoegsel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string achternaam {
            get {
                return this.achternaamField;
            }
            set {
                if ((object.ReferenceEquals(this.achternaamField, value) != true)) {
                    this.achternaamField = value;
                    this.RaisePropertyChanged("achternaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postcodeField, value) != true)) {
                    this.postcodeField = value;
                    this.RaisePropertyChanged("postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string woonplaats {
            get {
                return this.woonplaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.woonplaatsField, value) != true)) {
                    this.woonplaatsField = value;
                    this.RaisePropertyChanged("woonplaats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string telefoonnummer {
            get {
                return this.telefoonnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoonnummerField, value) != true)) {
                    this.telefoonnummerField = value;
                    this.RaisePropertyChanged("telefoonnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string emailadres {
            get {
                return this.emailadresField;
            }
            set {
                if ((object.ReferenceEquals(this.emailadresField, value) != true)) {
                    this.emailadresField = value;
                    this.RaisePropertyChanged("emailadres");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leasemaatschappij", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.SerializableAttribute()]
    public partial class Leasemaatschappij : Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Klant {
        
        private string naamField;
        
        private string adresField;
        
        private string postcodeField;
        
        private string woonplaatsField;
        
        private string telefoonnummerField;
        
        private string emailadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string naam {
            get {
                return this.naamField;
            }
            set {
                if ((object.ReferenceEquals(this.naamField, value) != true)) {
                    this.naamField = value;
                    this.RaisePropertyChanged("naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string adres {
            get {
                return this.adresField;
            }
            set {
                if ((object.ReferenceEquals(this.adresField, value) != true)) {
                    this.adresField = value;
                    this.RaisePropertyChanged("adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postcodeField, value) != true)) {
                    this.postcodeField = value;
                    this.RaisePropertyChanged("postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string woonplaats {
            get {
                return this.woonplaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.woonplaatsField, value) != true)) {
                    this.woonplaatsField = value;
                    this.RaisePropertyChanged("woonplaats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string telefoonnummer {
            get {
                return this.telefoonnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoonnummerField, value) != true)) {
                    this.telefoonnummerField = value;
                    this.RaisePropertyChanged("telefoonnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string emailadres {
            get {
                return this.emailadresField;
            }
            set {
                if ((object.ReferenceEquals(this.emailadresField, value) != true)) {
                    this.emailadresField = value;
                    this.RaisePropertyChanged("emailadres");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekResponseMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    [System.SerializableAttribute()]
    public partial class SendRdwKeuringsverzoekResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KentekenField;
        
        private Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Keuringsverzoek KeuringsverzoekField;
        
        private bool SteekproefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Kenteken {
            get {
                return this.KentekenField;
            }
            set {
                if ((object.ReferenceEquals(this.KentekenField, value) != true)) {
                    this.KentekenField = value;
                    this.RaisePropertyChanged("Kenteken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.Keuringsverzoek Keuringsverzoek {
            get {
                return this.KeuringsverzoekField;
            }
            set {
                if ((object.ReferenceEquals(this.KeuringsverzoekField, value) != true)) {
                    this.KeuringsverzoekField = value;
                    this.RaisePropertyChanged("Keuringsverzoek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Steekproef {
            get {
                return this.SteekproefField;
            }
            set {
                if ((this.SteekproefField.Equals(value) != true)) {
                    this.SteekproefField = value;
                    this.RaisePropertyChanged("Steekproef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:case2:isrijksdienstwegverkeer:v1", ConfigurationName="ISRDWServiceReferenceService.IISRDWService")]
    public interface IISRDWService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoek", ReplyAction="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekResponse" +
            "")]
        Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.SendRdwKeuringsverzoekRequestMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IISRDWServiceChannel : Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.IISRDWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ISRDWServiceClient : System.ServiceModel.ClientBase<Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.IISRDWService>, Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.IISRDWService {
        
        public ISRDWServiceClient() {
        }
        
        public ISRDWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ISRDWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISRDWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISRDWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(Minor.Case2.FEGMS.Client.ISRDWServiceReferenceService.SendRdwKeuringsverzoekRequestMessage message) {
            return base.Channel.RequestKeuringsverzoek(message);
        }
    }
}
