//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class apkKeuringsverzoekRequestMessage {
    
    private keuringsverzoek keuringsverzoekField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl")]
    public keuringsverzoek keuringsverzoek {
        get {
            return this.keuringsverzoekField;
        }
        set {
            this.keuringsverzoekField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rdw.nl", IsNullable=false)]
public partial class keuringsverzoek {
    
    private keuringsverzoekVoertuig voertuigField;
    
    private System.DateTime keuringsdatumField;
    
    private keuringsinstantie keuringsinstantieField;
    
    private string correlatieIdField;
    
    /// <remarks/>
    public keuringsverzoekVoertuig voertuig {
        get {
            return this.voertuigField;
        }
        set {
            this.voertuigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk", DataType="date")]
    public System.DateTime keuringsdatum {
        get {
            return this.keuringsdatumField;
        }
        set {
            this.keuringsdatumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk")]
    public keuringsinstantie keuringsinstantie {
        get {
            return this.keuringsinstantieField;
        }
        set {
            this.keuringsinstantieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string correlatieId {
        get {
            return this.correlatieIdField;
        }
        set {
            this.correlatieIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl")]
public partial class keuringsverzoekVoertuig {
    
    private string kentekenField;
    
    private ushort kilometerstandField;
    
    private string naamField;
    
    private string typeField;
    
    /// <remarks/>
    public string kenteken {
        get {
            return this.kentekenField;
        }
        set {
            this.kentekenField = value;
        }
    }
    
    /// <remarks/>
    public ushort kilometerstand {
        get {
            return this.kilometerstandField;
        }
        set {
            this.kilometerstandField = value;
        }
    }
    
    /// <remarks/>
    public string naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl/apk")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rdw.nl/apk", IsNullable=false)]
public partial class keuringsinstantie {
    
    private string naamField;
    
    private string plaatsField;
    
    private string typeField;
    
    private string kvkField;
    
    /// <remarks/>
    public string naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <remarks/>
    public string plaats {
        get {
            return this.plaatsField;
        }
        set {
            this.plaatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kvk {
        get {
            return this.kvkField;
        }
        set {
            this.kvkField = value;
        }
    }
}
