//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-isrijksdienstwegverkeer:v1:messages", ClrNamespace="minorcase2isrijksdienstwegverkeer.v1.messages")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-bsvoertuigenklantbeheer:v1:schema", ClrNamespace="minorcase2bsvoertuigenklantbeheer.v1.schema")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-isrijksdienstwegverkeer:v1:schema", ClrNamespace="minorcase2isrijksdienstwegverkeer.v1.schema")]

namespace minorcase2isrijksdienstwegverkeer.v1.messages
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekRequestMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    public partial class SendRdwKeuringsverzoekRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private minorcase2bsvoertuigenklantbeheer.v1.schema.Voertuig VoertuigField;
        
        private minorcase2isrijksdienstwegverkeer.v1.schema.Garage GarageField;
        
        private minorcase2isrijksdienstwegverkeer.v1.schema.Keuringsverzoek KeuringsverzoekField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public minorcase2bsvoertuigenklantbeheer.v1.schema.Voertuig Voertuig
        {
            get
            {
                return this.VoertuigField;
            }
            set
            {
                this.VoertuigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public minorcase2isrijksdienstwegverkeer.v1.schema.Garage Garage
        {
            get
            {
                return this.GarageField;
            }
            set
            {
                this.GarageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public minorcase2isrijksdienstwegverkeer.v1.schema.Keuringsverzoek Keuringsverzoek
        {
            get
            {
                return this.KeuringsverzoekField;
            }
            set
            {
                this.KeuringsverzoekField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekResponseMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    public partial class SendRdwKeuringsverzoekResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KentekenField;
        
        private minorcase2isrijksdienstwegverkeer.v1.schema.Keuringsverzoek KeuringsverzoekField;
        
        private bool SteekproefField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Kenteken
        {
            get
            {
                return this.KentekenField;
            }
            set
            {
                this.KentekenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public minorcase2isrijksdienstwegverkeer.v1.schema.Keuringsverzoek Keuringsverzoek
        {
            get
            {
                return this.KeuringsverzoekField;
            }
            set
            {
                this.KeuringsverzoekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Steekproef
        {
            get
            {
                return this.SteekproefField;
            }
            set
            {
                this.SteekproefField = value;
            }
        }
    }
}
namespace minorcase2bsvoertuigenklantbeheer.v1.schema
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voertuig", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Voertuig : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private string kentekenField;
        
        private string merkField;
        
        private string typeField;
        
        private minorcase2bsvoertuigenklantbeheer.v1.schema.Klant eigenaarField;
        
        private minorcase2bsvoertuigenklantbeheer.v1.schema.Persoon bestuurderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string kenteken
        {
            get
            {
                return this.kentekenField;
            }
            set
            {
                this.kentekenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string merk
        {
            get
            {
                return this.merkField;
            }
            set
            {
                this.merkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public minorcase2bsvoertuigenklantbeheer.v1.schema.Klant eigenaar
        {
            get
            {
                return this.eigenaarField;
            }
            set
            {
                this.eigenaarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public minorcase2bsvoertuigenklantbeheer.v1.schema.Persoon bestuurder
        {
            get
            {
                return this.bestuurderField;
            }
            set
            {
                this.bestuurderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klant", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(minorcase2bsvoertuigenklantbeheer.v1.schema.Persoon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(minorcase2bsvoertuigenklantbeheer.v1.schema.Leasemaatschappij))]
    public partial class Klant : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private long klantnummerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long klantnummer
        {
            get
            {
                return this.klantnummerField;
            }
            set
            {
                this.klantnummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoon", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Persoon : minorcase2bsvoertuigenklantbeheer.v1.schema.Klant
    {
        
        private string voornaamField;
        
        private string tussenvoegselField;
        
        private string achternaamField;
        
        private string adresField;
        
        private string postcodeField;
        
        private string woonplaatsField;
        
        private string telefoonnummerField;
        
        private string emailadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string voornaam
        {
            get
            {
                return this.voornaamField;
            }
            set
            {
                this.voornaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string tussenvoegsel
        {
            get
            {
                return this.tussenvoegselField;
            }
            set
            {
                this.tussenvoegselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string achternaam
        {
            get
            {
                return this.achternaamField;
            }
            set
            {
                this.achternaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string woonplaats
        {
            get
            {
                return this.woonplaatsField;
            }
            set
            {
                this.woonplaatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string telefoonnummer
        {
            get
            {
                return this.telefoonnummerField;
            }
            set
            {
                this.telefoonnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string emailadres
        {
            get
            {
                return this.emailadresField;
            }
            set
            {
                this.emailadresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leasemaatschappij", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Leasemaatschappij : minorcase2bsvoertuigenklantbeheer.v1.schema.Klant
    {
        
        private string naamField;
        
        private string adresField;
        
        private string postcodeField;
        
        private string woonplaatsField;
        
        private string telefoonnummerField;
        
        private string emailadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string naam
        {
            get
            {
                return this.naamField;
            }
            set
            {
                this.naamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string woonplaats
        {
            get
            {
                return this.woonplaatsField;
            }
            set
            {
                this.woonplaatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string telefoonnummer
        {
            get
            {
                return this.telefoonnummerField;
            }
            set
            {
                this.telefoonnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string emailadres
        {
            get
            {
                return this.emailadresField;
            }
            set
            {
                this.emailadresField = value;
            }
        }
    }
}
namespace minorcase2isrijksdienstwegverkeer.v1.schema
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Garage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    public partial class Garage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NaamField;
        
        private string PlaatsField;
        
        private string KvkField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Plaats
        {
            get
            {
                return this.PlaatsField;
            }
            set
            {
                this.PlaatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Kvk
        {
            get
            {
                return this.KvkField;
            }
            set
            {
                this.KvkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keuringsverzoek", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    public partial class Keuringsverzoek : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string CorrolatieIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CorrolatieId
        {
            get
            {
                return this.CorrolatieIdField;
            }
            set
            {
                this.CorrolatieIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:case2:isrijksdienstwegverkeer:v1", ConfigurationName="IISRDWService")]
public interface IISRDWService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoek", ReplyAction="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekResponse" +
        "")]
    minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekRequestMessage message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoek", ReplyAction="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekResponse" +
        "")]
    System.Threading.Tasks.Task<minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekResponseMessage> RequestKeuringsverzoekAsync(minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekRequestMessage message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IISRDWServiceChannel : IISRDWService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ISRDWServiceClient : System.ServiceModel.ClientBase<IISRDWService>, IISRDWService
{
    
    public ISRDWServiceClient()
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ISRDWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekRequestMessage message)
    {
        return base.Channel.RequestKeuringsverzoek(message);
    }
    
    public System.Threading.Tasks.Task<minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekResponseMessage> RequestKeuringsverzoekAsync(minorcase2isrijksdienstwegverkeer.v1.messages.SendRdwKeuringsverzoekRequestMessage message)
    {
        return base.Channel.RequestKeuringsverzoekAsync(message);
    }
}
