//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-isrijksdienstwegverkeer:v1:messages", ClrNamespace="Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-bsvoertuigenklantbeheer:v1:schema", ClrNamespace="Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-isrijksdienstwegverkeer:v1:schema", ClrNamespace="Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:minor-case2-all:v1:schema", ClrNamespace="Minor.Case2.Exceptions.V1.Schema")]

namespace Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekRequestMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    public partial class SendRdwKeuringsverzoekRequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig VoertuigField;
        
        private Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Garage GarageField;
        
        private Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Keuringsverzoek KeuringsverzoekField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig Voertuig
        {
            get
            {
                return this.VoertuigField;
            }
            set
            {
                this.VoertuigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Garage Garage
        {
            get
            {
                return this.GarageField;
            }
            set
            {
                this.GarageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Keuringsverzoek Keuringsverzoek
        {
            get
            {
                return this.KeuringsverzoekField;
            }
            set
            {
                this.KeuringsverzoekField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendRdwKeuringsverzoekResponseMessage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:messages")]
    public partial class SendRdwKeuringsverzoekResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KentekenField;
        
        private Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Keuringsverzoek KeuringsverzoekField;
        
        private bool SteekproefField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Kenteken
        {
            get
            {
                return this.KentekenField;
            }
            set
            {
                this.KentekenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Keuringsverzoek Keuringsverzoek
        {
            get
            {
                return this.KeuringsverzoekField;
            }
            set
            {
                this.KeuringsverzoekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Steekproef
        {
            get
            {
                return this.SteekproefField;
            }
            set
            {
                this.SteekproefField = value;
            }
        }
    }
}
namespace Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voertuig", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Voertuig : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private string KentekenField;
        
        private string MerkField;
        
        private string TypeField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant EigenaarField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon BestuurderField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Kenteken
        {
            get
            {
                return this.KentekenField;
            }
            set
            {
                this.KentekenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Merk
        {
            get
            {
                return this.MerkField;
            }
            set
            {
                this.MerkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant Eigenaar
        {
            get
            {
                return this.EigenaarField;
            }
            set
            {
                this.EigenaarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon Bestuurder
        {
            get
            {
                return this.BestuurderField;
            }
            set
            {
                this.BestuurderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klant", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Leasemaatschappij))]
    public partial class Klant : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private long KlantnummerField;
        
        private string TelefoonnummerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Klantnummer
        {
            get
            {
                return this.KlantnummerField;
            }
            set
            {
                this.KlantnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Telefoonnummer
        {
            get
            {
                return this.TelefoonnummerField;
            }
            set
            {
                this.TelefoonnummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoon", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Persoon : Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant
    {
        
        private string VoornaamField;
        
        private string TussenvoegselField;
        
        private string AchternaamField;
        
        private string AdresField;
        
        private string PostcodeField;
        
        private string WoonplaatsField;
        
        private string EmailadresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Voornaam
        {
            get
            {
                return this.VoornaamField;
            }
            set
            {
                this.VoornaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Tussenvoegsel
        {
            get
            {
                return this.TussenvoegselField;
            }
            set
            {
                this.TussenvoegselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Achternaam
        {
            get
            {
                return this.AchternaamField;
            }
            set
            {
                this.AchternaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Postcode
        {
            get
            {
                return this.PostcodeField;
            }
            set
            {
                this.PostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Woonplaats
        {
            get
            {
                return this.WoonplaatsField;
            }
            set
            {
                this.WoonplaatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Emailadres
        {
            get
            {
                return this.EmailadresField;
            }
            set
            {
                this.EmailadresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leasemaatschappij", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Leasemaatschappij : Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant
    {
        
        private string NaamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="KlantenCollection", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema", ItemName="Klant")]
    public class KlantenCollection : System.Collections.Generic.List<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnderhoudsopdrachtZoekCriteria", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class OnderhoudsopdrachtZoekCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> IDField;
        
        private System.Nullable<System.DateTime> AanmeldingsdatumField;
        
        private System.Nullable<long> KilometerstandField;
        
        private string OnderhoudsomschrijvingField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria VoertuigenSearchCriteriaField;
        
        private System.Nullable<bool> APKField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<System.DateTime> Aanmeldingsdatum
        {
            get
            {
                return this.AanmeldingsdatumField;
            }
            set
            {
                this.AanmeldingsdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> Kilometerstand
        {
            get
            {
                return this.KilometerstandField;
            }
            set
            {
                this.KilometerstandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Onderhoudsomschrijving
        {
            get
            {
                return this.OnderhoudsomschrijvingField;
            }
            set
            {
                this.OnderhoudsomschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria VoertuigenSearchCriteria
        {
            get
            {
                return this.VoertuigenSearchCriteriaField;
            }
            set
            {
                this.VoertuigenSearchCriteriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> APK
        {
            get
            {
                return this.APKField;
            }
            set
            {
                this.APKField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoertuigenSearchCriteria", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class VoertuigenSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private string KentekenField;
        
        private string MerkField;
        
        private string TypeField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant EigenaarField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon BestuurderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Kenteken
        {
            get
            {
                return this.KentekenField;
            }
            set
            {
                this.KentekenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Merk
        {
            get
            {
                return this.MerkField;
            }
            set
            {
                this.MerkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant Eigenaar
        {
            get
            {
                return this.EigenaarField;
            }
            set
            {
                this.EigenaarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon Bestuurder
        {
            get
            {
                return this.BestuurderField;
            }
            set
            {
                this.BestuurderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OnderhoudsopdrachtenCollection", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema", ItemName="Onderhoudsopdracht")]
    public class OnderhoudsopdrachtenCollection : System.Collections.Generic.List<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Onderhoudsopdracht", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Onderhoudsopdracht : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private System.DateTime AanmeldingsdatumField;
        
        private long KilometerstandField;
        
        private string OnderhoudsomschrijvingField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig VoertuigField;
        
        private bool APKField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden OnderhoudswerkzaamhedenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Aanmeldingsdatum
        {
            get
            {
                return this.AanmeldingsdatumField;
            }
            set
            {
                this.AanmeldingsdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Kilometerstand
        {
            get
            {
                return this.KilometerstandField;
            }
            set
            {
                this.KilometerstandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Onderhoudsomschrijving
        {
            get
            {
                return this.OnderhoudsomschrijvingField;
            }
            set
            {
                this.OnderhoudsomschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig Voertuig
        {
            get
            {
                return this.VoertuigField;
            }
            set
            {
                this.VoertuigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool APK
        {
            get
            {
                return this.APKField;
            }
            set
            {
                this.APKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden Onderhoudswerkzaamheden
        {
            get
            {
                return this.OnderhoudswerkzaamhedenField;
            }
            set
            {
                this.OnderhoudswerkzaamhedenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Onderhoudswerkzaamheden", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema")]
    public partial class Onderhoudswerkzaamheden : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private System.DateTime AfmeldingsdatumField;
        
        private long KilometerstandField;
        
        private string OnderhoudswerkzaamhedenomschrijvingField;
        
        private Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht OnderhoudsopdrachtField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Afmeldingsdatum
        {
            get
            {
                return this.AfmeldingsdatumField;
            }
            set
            {
                this.AfmeldingsdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Kilometerstand
        {
            get
            {
                return this.KilometerstandField;
            }
            set
            {
                this.KilometerstandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Onderhoudswerkzaamhedenomschrijving
        {
            get
            {
                return this.OnderhoudswerkzaamhedenomschrijvingField;
            }
            set
            {
                this.OnderhoudswerkzaamhedenomschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht Onderhoudsopdracht
        {
            get
            {
                return this.OnderhoudsopdrachtField;
            }
            set
            {
                this.OnderhoudsopdrachtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="VoertuigenCollection", Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1:schema", ItemName="Voertuig")]
    public class VoertuigenCollection : System.Collections.Generic.List<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig>
    {
    }
}
namespace Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Garage", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    public partial class Garage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NaamField;
        
        private string PlaatsField;
        
        private string KvkField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Naam
        {
            get
            {
                return this.NaamField;
            }
            set
            {
                this.NaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Plaats
        {
            get
            {
                return this.PlaatsField;
            }
            set
            {
                this.PlaatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Kvk
        {
            get
            {
                return this.KvkField;
            }
            set
            {
                this.KvkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keuringsverzoek", Namespace="urn:minor-case2-isrijksdienstwegverkeer:v1:schema")]
    public partial class Keuringsverzoek : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string CorrolatieIdField;
        
        private int KilometerstandField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CorrolatieId
        {
            get
            {
                return this.CorrolatieIdField;
            }
            set
            {
                this.CorrolatieIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Kilometerstand
        {
            get
            {
                return this.KilometerstandField;
            }
            set
            {
                this.KilometerstandField = value;
            }
        }
    }
}
namespace Minor.Case2.Exceptions.V1.Schema
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionalErrorDetail", Namespace="urn:minor-case2-all:v1:schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.Exceptions.V1.Schema.FunctionalErrorDetail[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekRequestMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekResponseMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Garage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.ISRijksdienstWegverkeerService.V1.Schema.Agent.Keuringsverzoek))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Klant))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Persoon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Leasemaatschappij))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtZoekCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtenCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenCollection))]
    public partial class FunctionalErrorDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private object DataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public object Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:case2:isrijksdienstwegverkeer:v1", ConfigurationName="IISRDWService")]
public interface IISRDWService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoek", ReplyAction="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekResponse" +
        "")]
    [System.ServiceModel.FaultContractAttribute(typeof(Minor.Case2.Exceptions.V1.Schema.FunctionalErrorDetail[]), Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekArrayOfF" +
        "unctionalErrorDetailFault", Name="ArrayOfFunctionalErrorDetail", Namespace="urn:minor-case2-all:v1:schema")]
    Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekRequestMessage message);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoek", ReplyAction="urn:case2:isrijksdienstwegverkeer:v1/IISRDWService/RequestKeuringsverzoekResponse" +
        "")]
    System.Threading.Tasks.Task<Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekResponseMessage> RequestKeuringsverzoekAsync(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekRequestMessage message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IISRDWServiceChannel : IISRDWService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ISRDWServiceClient : System.ServiceModel.ClientBase<IISRDWService>, IISRDWService
{
    
    public ISRDWServiceClient()
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ISRDWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ISRDWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekResponseMessage RequestKeuringsverzoek(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekRequestMessage message)
    {
        return base.Channel.RequestKeuringsverzoek(message);
    }
    
    public System.Threading.Tasks.Task<Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekResponseMessage> RequestKeuringsverzoekAsync(Minor.Case2.ISRijksdienstWegverkeerService.V1.Messages.Agent.SendRdwKeuringsverzoekRequestMessage message)
    {
        return base.Channel.RequestKeuringsverzoekAsync(message);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:minor-case2-bsvoertuigenklantbeheer:v1", ConfigurationName="IBSVoertuigEnKlantbeheer")]
public interface IBSVoertuigEnKlantbeheer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllKlanten" +
        "", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllKlanten" +
        "Response")]
    Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection GetAllKlanten();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllKlanten" +
        "", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllKlanten" +
        "Response")]
    System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection> GetAllKlantenAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllLeasema" +
        "atschappijen", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllLeasema" +
        "atschappijenResponse")]
    Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection GetAllLeasemaatschappijen();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllLeasema" +
        "atschappijen", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetAllLeasema" +
        "atschappijenResponse")]
    System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection> GetAllLeasemaatschappijenAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetOnderhouds" +
        "opdrachtenBy", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetOnderhouds" +
        "opdrachtenByResponse")]
    Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtenCollection GetOnderhoudsopdrachtenBy(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtZoekCriteria zoekCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetOnderhouds" +
        "opdrachtenBy", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetOnderhouds" +
        "opdrachtenByResponse")]
    System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtenCollection> GetOnderhoudsopdrachtenByAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtZoekCriteria zoekCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetVoertuigBy" +
        "", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetVoertuigBy" +
        "Response")]
    Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenCollection GetVoertuigBy(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria zoekCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetVoertuigBy" +
        "", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/GetVoertuigBy" +
        "Response")]
    System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenCollection> GetVoertuigByAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria zoekCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegVoertuigM" +
        "etKlantToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegVoertuigM" +
        "etKlantToeResponse")]
    void VoegVoertuigMetKlantToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegVoertuigM" +
        "etKlantToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegVoertuigM" +
        "etKlantToeResponse")]
    System.Threading.Tasks.Task VoegVoertuigMetKlantToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "sopdrachtToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "sopdrachtToeResponse")]
    void VoegOnderhoudsopdrachtToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht onderhoudsopdracht);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "sopdrachtToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "sopdrachtToeResponse")]
    System.Threading.Tasks.Task VoegOnderhoudsopdrachtToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht onderhoudsopdracht);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "swerkzaamhedenToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "swerkzaamhedenToeResponse")]
    void VoegOnderhoudswerkzaamhedenToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden onderhoudswerkzaamheden);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "swerkzaamhedenToe", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/VoegOnderhoud" +
        "swerkzaamhedenToeResponse")]
    System.Threading.Tasks.Task VoegOnderhoudswerkzaamhedenToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden onderhoudswerkzaamheden);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/UpdateVoertui" +
        "g", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/UpdateVoertui" +
        "gResponse")]
    void UpdateVoertuig(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/UpdateVoertui" +
        "g", ReplyAction="urn:minor-case2-bsvoertuigenklantbeheer:v1/IBSVoertuigEnKlantbeheer/UpdateVoertui" +
        "gResponse")]
    System.Threading.Tasks.Task UpdateVoertuigAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBSVoertuigEnKlantbeheerChannel : IBSVoertuigEnKlantbeheer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BSVoertuigEnKlantbeheerClient : System.ServiceModel.ClientBase<IBSVoertuigEnKlantbeheer>, IBSVoertuigEnKlantbeheer
{
    
    public BSVoertuigEnKlantbeheerClient()
    {
    }
    
    public BSVoertuigEnKlantbeheerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BSVoertuigEnKlantbeheerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BSVoertuigEnKlantbeheerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BSVoertuigEnKlantbeheerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection GetAllKlanten()
    {
        return base.Channel.GetAllKlanten();
    }
    
    public System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection> GetAllKlantenAsync()
    {
        return base.Channel.GetAllKlantenAsync();
    }
    
    public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection GetAllLeasemaatschappijen()
    {
        return base.Channel.GetAllLeasemaatschappijen();
    }
    
    public System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.KlantenCollection> GetAllLeasemaatschappijenAsync()
    {
        return base.Channel.GetAllLeasemaatschappijenAsync();
    }
    
    public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtenCollection GetOnderhoudsopdrachtenBy(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtZoekCriteria zoekCriteria)
    {
        return base.Channel.GetOnderhoudsopdrachtenBy(zoekCriteria);
    }
    
    public System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtenCollection> GetOnderhoudsopdrachtenByAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.OnderhoudsopdrachtZoekCriteria zoekCriteria)
    {
        return base.Channel.GetOnderhoudsopdrachtenByAsync(zoekCriteria);
    }
    
    public Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenCollection GetVoertuigBy(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria zoekCriteria)
    {
        return base.Channel.GetVoertuigBy(zoekCriteria);
    }
    
    public System.Threading.Tasks.Task<Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenCollection> GetVoertuigByAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.VoertuigenSearchCriteria zoekCriteria)
    {
        return base.Channel.GetVoertuigByAsync(zoekCriteria);
    }
    
    public void VoegVoertuigMetKlantToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig)
    {
        base.Channel.VoegVoertuigMetKlantToe(voertuig);
    }
    
    public System.Threading.Tasks.Task VoegVoertuigMetKlantToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig)
    {
        return base.Channel.VoegVoertuigMetKlantToeAsync(voertuig);
    }
    
    public void VoegOnderhoudsopdrachtToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht onderhoudsopdracht)
    {
        base.Channel.VoegOnderhoudsopdrachtToe(onderhoudsopdracht);
    }
    
    public System.Threading.Tasks.Task VoegOnderhoudsopdrachtToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudsopdracht onderhoudsopdracht)
    {
        return base.Channel.VoegOnderhoudsopdrachtToeAsync(onderhoudsopdracht);
    }
    
    public void VoegOnderhoudswerkzaamhedenToe(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden onderhoudswerkzaamheden)
    {
        base.Channel.VoegOnderhoudswerkzaamhedenToe(onderhoudswerkzaamheden);
    }
    
    public System.Threading.Tasks.Task VoegOnderhoudswerkzaamhedenToeAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Onderhoudswerkzaamheden onderhoudswerkzaamheden)
    {
        return base.Channel.VoegOnderhoudswerkzaamhedenToeAsync(onderhoudswerkzaamheden);
    }
    
    public void UpdateVoertuig(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig)
    {
        base.Channel.UpdateVoertuig(voertuig);
    }
    
    public System.Threading.Tasks.Task UpdateVoertuigAsync(Minor.Case2.BSVoertuigenEnKlantBeheer.V1.Schema.Agent.Voertuig voertuig)
    {
        return base.Channel.UpdateVoertuigAsync(voertuig);
    }
}
